In [26]:
import numpy as np

#Declaration of array


scores = np.array([[85, 90, 78],
                   [92, 88, 95],
                   [76, 95, 85],
                   [90, 85, 92],
                   [88, 76, 89]])
scores

array([[85, 90, 78],
       [92, 88, 95],
       [76, 95, 85],
       [90, 85, 92],
       [88, 76, 89]])

In [27]:
#Calculate the mean score of each subject (across all subjects).

np.mean(scores,axis=0)

array([86.2, 86.8, 87.8])

In [28]:
#Find the median score of each student (across all subjects).

np.median(scores,axis=1)

array([85., 92., 85., 90., 88.])

In [29]:
#Reshape the array to have shape(3,5), where each row represents a subject and each column represents a student.

scores.reshape(3,5)

array([[85, 90, 78, 92, 88],
       [95, 76, 95, 85, 90],
       [85, 92, 88, 76, 89]])

In [30]:
#Sort the scores of each subject in ascending order.

np.sort(scores,axis=0)

array([[76, 76, 78],
       [85, 85, 85],
       [88, 88, 89],
       [90, 90, 92],
       [92, 95, 95]])

In [31]:
#Find the minimum scores in each subject.

np.min(scores,axis=0)

array([76, 76, 78])

In [32]:
#Find the maximum scores in each subject.

np.max(scores,axis=0)

array([92, 95, 95])

In [33]:
total = scores.sum(axis=1)
total

array([253, 275, 256, 267, 253])

In [34]:
np.max(total,axis=0)

np.int64(275)