In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
print(arr.dtype)

int64


In [4]:
arr2 = np.array([1,2,3,4,5],dtype=np.int16)
arr2

array([1, 2, 3, 4, 5], dtype=int16)

In [5]:
Z=np.zeros(5)
Z

array([0., 0., 0., 0., 0.])

In [6]:
ar=np.arange(0,10,1)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
ran=np.random.rand(4)
ran

array([0.68062202, 0.68276006, 0.59699768, 0.63095005])

In [8]:
ln=np.linspace(0,100,10)
ln

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

**2D Arrays**

In [9]:
ar2=np.array([[1,2,3],[4,5,6],[7,8,9]])
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
z1=np.zeros([5,5])
z1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
o1=np.ones([5,5])
o1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
I=np.eye(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
r1=np.random.rand(4,5)
r1

array([[0.60273326, 0.34302955, 0.12722741, 0.02760122, 0.41257096],
       [0.40475746, 0.81405167, 0.94236481, 0.21992896, 0.16258156],
       [0.61245278, 0.63504565, 0.6995252 , 0.2426425 , 0.6198635 ],
       [0.69955275, 0.5011721 , 0.07602536, 0.06105526, 0.82051285]])

In [14]:
ar
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
print(ar.size)

10


In [18]:
print(ar2.size)

9


In [19]:
print(ar.shape)

(10,)


**Operations in Array**
copy reshape sort

In [20]:
ar3=np.copy(ar2)
ar3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
ar3[2,2]=10

In [22]:
ar3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [23]:
ar3[1,2]=12
ar3[0,1]=15
ar3

array([[ 1, 15,  3],
       [ 4,  5, 12],
       [ 7,  8, 10]])

In [24]:
ar3=np.sort(ar3)
ar3

array([[ 1,  3, 15],
       [ 4,  5, 12],
       [ 7,  8, 10]])

In [25]:
ar3=np.sort(ar3,axis=0)
ar3

array([[ 1,  3, 10],
       [ 4,  5, 12],
       [ 7,  8, 15]])

In [26]:
ar3.sum()

np.int64(65)

In [27]:
ar3.sum(axis=0)

array([12, 16, 37])

In [28]:
ar3.sum(axis=1)

array([14, 21, 30])

In [29]:
ar4=np.random.rand(99)
ar4

array([0.23207219, 0.85700405, 0.11111337, 0.84108373, 0.49372641,
       0.19345132, 0.59141642, 0.65115508, 0.57161833, 0.83998976,
       0.69960206, 0.26121457, 0.15211088, 0.58367308, 0.62139498,
       0.79155572, 0.48156708, 0.26818   , 0.49435385, 0.40224817,
       0.12969303, 0.45205621, 0.84712457, 0.82362432, 0.90775154,
       0.02071414, 0.68357172, 0.4695172 , 0.41828243, 0.93387523,
       0.86207661, 0.67670029, 0.23296403, 0.64579865, 0.15217502,
       0.55001965, 0.78722238, 0.88030525, 0.20288938, 0.65407432,
       0.38362101, 0.89447625, 0.95707372, 0.86599072, 0.64669255,
       0.86349616, 0.65427636, 0.00700311, 0.65003354, 0.10871695,
       0.17893171, 0.57223386, 0.82585901, 0.78312556, 0.11209514,
       0.57415173, 0.46965404, 0.70952539, 0.07145321, 0.15862757,
       0.75195861, 0.25580273, 0.03894218, 0.05702385, 0.01069632,
       0.97103738, 0.24473901, 0.07431258, 0.27505493, 0.94099693,
       0.07495758, 0.32504359, 0.54326826, 0.74155169, 0.93847

In [30]:
ar4.size

99

In [31]:
ar4=ar4.reshape(11,9)

In [32]:
ar4.size

99

In [33]:
ar4.shape

(11, 9)

In [34]:
ar4

array([[0.23207219, 0.85700405, 0.11111337, 0.84108373, 0.49372641,
        0.19345132, 0.59141642, 0.65115508, 0.57161833],
       [0.83998976, 0.69960206, 0.26121457, 0.15211088, 0.58367308,
        0.62139498, 0.79155572, 0.48156708, 0.26818   ],
       [0.49435385, 0.40224817, 0.12969303, 0.45205621, 0.84712457,
        0.82362432, 0.90775154, 0.02071414, 0.68357172],
       [0.4695172 , 0.41828243, 0.93387523, 0.86207661, 0.67670029,
        0.23296403, 0.64579865, 0.15217502, 0.55001965],
       [0.78722238, 0.88030525, 0.20288938, 0.65407432, 0.38362101,
        0.89447625, 0.95707372, 0.86599072, 0.64669255],
       [0.86349616, 0.65427636, 0.00700311, 0.65003354, 0.10871695,
        0.17893171, 0.57223386, 0.82585901, 0.78312556],
       [0.11209514, 0.57415173, 0.46965404, 0.70952539, 0.07145321,
        0.15862757, 0.75195861, 0.25580273, 0.03894218],
       [0.05702385, 0.01069632, 0.97103738, 0.24473901, 0.07431258,
        0.27505493, 0.94099693, 0.07495758, 0.32504359],


In [35]:
ar3

array([[ 1,  3, 10],
       [ 4,  5, 12],
       [ 7,  8, 15]])

In [36]:
ar3=ar3.T
ar3

array([[ 1,  4,  7],
       [ 3,  5,  8],
       [10, 12, 15]])

In [37]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.append(ar,10)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
ar=np.delete(ar,6,axis=0)

In [41]:
ar

array([0, 1, 2, 3, 4, 5, 7, 8, 9])

In [42]:
ar=np.insert(ar,6,6)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
ar3

array([[ 1,  4,  7],
       [ 3,  5,  8],
       [10, 12, 15]])

In [45]:
ar4=np.concatenate((ar2,ar3),axis=0)
ar4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 1,  4,  7],
       [ 3,  5,  8],
       [10, 12, 15]])

In [46]:
ar5=np.concatenate((ar2,ar3),axis=1)
ar5

array([[ 1,  2,  3,  1,  4,  7],
       [ 4,  5,  6,  3,  5,  8],
       [ 7,  8,  9, 10, 12, 15]])

In [47]:
np.split(ar4,3)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9],
        [1, 4, 7]]),
 array([[ 3,  5,  8],
        [10, 12, 15]])]

In [48]:
ar6=np.split(ar4,3)
ar6

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9],
        [1, 4, 7]]),
 array([[ 3,  5,  8],
        [10, 12, 15]])]

In [49]:
ar6[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
ar6[2]

array([[ 3,  5,  8],
       [10, 12, 15]])

**Scalar Expressions**
add subtract multiply divide power

In [51]:
ar5

array([[ 1,  2,  3,  1,  4,  7],
       [ 4,  5,  6,  3,  5,  8],
       [ 7,  8,  9, 10, 12, 15]])

In [52]:
np.add(ar5,1)

array([[ 2,  3,  4,  2,  5,  8],
       [ 5,  6,  7,  4,  6,  9],
       [ 8,  9, 10, 11, 13, 16]])

**Vector Operations**

In [53]:
ar6

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9],
        [1, 4, 7]]),
 array([[ 3,  5,  8],
        [10, 12, 15]])]

In [54]:
ar7 = np.add(ar6[0],ar6[1])
ar7

array([[ 8, 10, 12],
       [ 5,  9, 13]])

In [55]:
ar8 = np.multiply(ar6[0],ar6[1])
ar8

array([[ 7, 16, 27],
       [ 4, 20, 42]])

In [56]:
ar9 = np.divide(ar6[0],ar6[1])
ar9

array([[0.14285714, 0.25      , 0.33333333],
       [4.        , 1.25      , 0.85714286]])

In [57]:
np.ceil(ar9)


array([[1., 1., 1.],
       [4., 2., 1.]])

In [58]:
np.floor(ar9)

array([[0., 0., 0.],
       [4., 1., 0.]])

In [59]:
np.round(ar9)

array([[0., 0., 0.],
       [4., 1., 1.]])

**Statistics**

In [60]:
np.mean(ar5)

np.float64(6.111111111111111)

In [61]:
np.mean(ar5,axis=0)

array([ 4.        ,  5.        ,  6.        ,  4.66666667,  7.        ,
       10.        ])

In [62]:
np.mean(ar5,axis=1)

array([ 3.        ,  5.16666667, 10.16666667])

In [63]:
np.median(ar5)

np.float64(5.5)

In [64]:
np.median(ar5,axis=1)

array([2.5, 5. , 9.5])

In [65]:
np.min(ar5)

np.int64(1)

In [66]:
np.min(ar5,axis=0)

array([1, 2, 3, 1, 4, 7])

In [67]:
np.max(ar5,axis=0)

array([ 7,  8,  9, 10, 12, 15])

In [68]:
ar10=np.array([2,5,3,8,0,4,1,6,9])

In [69]:
ar5

array([[ 1,  2,  3,  1,  4,  7],
       [ 4,  5,  6,  3,  5,  8],
       [ 7,  8,  9, 10, 12, 15]])